/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiproject;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import se.chalmers.ait.dat215.project.IMatDataHandler;
import se.chalmers.ait.dat215.project.Product;
import se.chalmers.ait.dat215.project.ShoppingItem;

/**
 *
 * @author Jenny
 */
public class CheckoutProductCard extends javax.swing.JPanel {

    private IMatDataHandler dataHandler = IMatDataHandler.getInstance();
    private Product product;
    boolean pinkBG;

    /**
     * Creates new form CheckoutProductCard
     */

    public CheckoutProductCard(ShoppingItem si, IMatFrame imf, boolean pinkBG){
        initComponents();
        this.pinkBG = pinkBG;
        this.product = si.getProduct();
        
        updateLabels(si, imf);
        
        if (pinkBG){
            checkoutProductIcon.setBackground(new java.awt.Color(215,173,173));
            setBackground(new java.awt.Color(215,173,173));
        } 
        
    }
    
    public void updateLabels(ShoppingItem si, IMatFrame imf){
        this.checkoutProductLabel.setText(product.getName());
        this.checkoutProductIcon.setIcon(imf.gpCon.getImageCustom(product, 100, 100));
        checkoutAmountLabel.setText(si.getProduct().getPrice() + si.getProduct().getUnit() + " x " + si.getAmount());
        checkoutTotalPriceLabel.setText("Totalt: "+si.getTotal() + " kr");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkoutProductIcon = new javax.swing.JLabel();
        checkoutProductLabel = new javax.swing.JLabel();
        checkoutAmountLabel = new javax.swing.JLabel();
        checkoutTotalPriceLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 248, 248));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, null));

        checkoutProductIcon.setBackground(new java.awt.Color(255, 255, 255));
        checkoutProductIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiKundvagn.png"))); // NOI18N
        checkoutProductIcon.setMaximumSize(new java.awt.Dimension(50, 50));
        checkoutProductIcon.setMinimumSize(new java.awt.Dimension(50, 50));
        checkoutProductIcon.setPreferredSize(new java.awt.Dimension(50, 50));

        checkoutProductLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkoutProductLabel.setForeground(new java.awt.Color(51, 51, 51));
        checkoutProductLabel.setText("Produktnamn");

        checkoutAmountLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkoutAmountLabel.setText("xst");

        checkoutTotalPriceLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkoutTotalPriceLabel.setText("totkr");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkoutProductIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkoutProductLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkoutAmountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addGap(41, 41, 41)
                .addComponent(checkoutTotalPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(checkoutProductIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkoutProductLabel)
                            .addComponent(checkoutAmountLabel)
                            .addComponent(checkoutTotalPriceLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel checkoutAmountLabel;
    private javax.swing.JLabel checkoutProductIcon;
    private javax.swing.JLabel checkoutProductLabel;
    private javax.swing.JLabel checkoutTotalPriceLabel;
    // End of variables declaration//GEN-END:variables
}

