/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiproject;

import java.awt.Component;
import se.chalmers.ait.dat215.project.*;

/**
 *
 * @author RebeckaReitmaier
 */
public class ProductCard extends javax.swing.JPanel {

    /**
     * Creates new form ProductCard1
     */
    
    GUIProject gpCon = new GUIProject();
    
    public ProductCard(Product prod) {
        initComponents();
        this.pictureLabel.setIcon(gpCon.getImage(prod));
//        this.productName = searchField.getInputContext(); //hur ska man skriva?
        this.productCardName.setText(prod.getName());
       }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Body = new javax.swing.JPanel();
        Head = new javax.swing.JPanel();
        pictureLabel = new javax.swing.JLabel();
        productCardName = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        Body.setBackground(new java.awt.Color(204, 255, 204));
        add(Body, java.awt.BorderLayout.CENTER);

        Head.setBackground(new java.awt.Color(0, 204, 204));
        Head.add(pictureLabel);

        productCardName.setText("jLabel1");
        Head.add(productCardName);

        add(Head, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JPanel Head;
    private javax.swing.JLabel pictureLabel;
    private javax.swing.JLabel productCardName;
    // End of variables declaration//GEN-END:variables
}
