/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiproject;

import java.awt.Color;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import se.chalmers.ait.dat215.project.IMatDataHandler;

/**
 *
 * @author Jenny
 */
public class UserPanel extends javax.swing.JPanel {
    /**
     * Creates new form UserPanel
     */
    public UserPanel() {
        initComponents();
        
        if(!IMatDataHandler.getInstance().getCustomer().getFirstName().equals("") &&
                !IMatDataHandler.getInstance().getCustomer().getLastName().equals("")){
            
            titleNameLabel.setText(IMatDataHandler.getInstance().getCustomer().getFirstName() +
                    " " + IMatDataHandler.getInstance().getCustomer().getLastName());
        } else{
            titleNameLabel.setText("");
        }
        
        // Sets values for text fields in "Personal information"
        firstNameTextField.setText(IMatDataHandler.getInstance().getCustomer().getFirstName());
        lastNameTextField.setText(IMatDataHandler.getInstance().getCustomer().getLastName());
        address1TextField.setText(IMatDataHandler.getInstance().getCustomer().getAddress());
        postCodeTextField.setText(IMatDataHandler.getInstance().getCustomer().getPostCode());
        emailTextField.setText(IMatDataHandler.getInstance().getCustomer().getEmail());
        phoneNumberTextField.setText(IMatDataHandler.getInstance().getCustomer().getPhoneNumber());
        
        // Sets values for text fields and comboboxes in "Payment"
        cardNumberTextField.setText(IMatDataHandler.getInstance().getCreditCard().getCardNumber());
        validMonthComboBox.setSelectedIndex(iMDH.getCreditCard().getValidMonth());
        validYearComboBox.setSelectedIndex(iMDH.getCreditCard().getValidYear());
        verificationCodeTextField.setText(IMatDataHandler.getInstance().getCreditCard().getVerificationCode() + "");
        cardHolderTextField.setText(IMatDataHandler.getInstance().getCreditCard().getHoldersName());
        
        // Sets values for combo- and checkboxes in "Delivery"
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        personalInfoPanel = new javax.swing.JPanel();
        personalInfoLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        address1TextField = new javax.swing.JTextField();
        adress1Label = new javax.swing.JLabel();
        address2TextField = new javax.swing.JTextField();
        adress2Label = new javax.swing.JLabel();
        postCodeLabel = new javax.swing.JLabel();
        postCodeTextField = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        separator1 = new javax.swing.JLabel();
        phoneNumberTextField = new javax.swing.JTextField();
        phoneNumberLabel = new javax.swing.JLabel();
        paymentInfoPanel = new javax.swing.JPanel();
        paymentInfoLabel = new javax.swing.JLabel();
        cardNumberLabel = new javax.swing.JLabel();
        cardNumberTextField = new javax.swing.JTextField();
        cardTypeComboBox = new javax.swing.JComboBox();
        cardTypeLabel = new javax.swing.JLabel();
        expirationDateLabel = new javax.swing.JLabel();
        validMonthComboBox = new javax.swing.JComboBox();
        expDateSlashLabel = new javax.swing.JLabel();
        validYearComboBox = new javax.swing.JComboBox();
        verificationCodeLabel = new javax.swing.JLabel();
        verificationCodeTextField = new javax.swing.JTextField();
        cardHolderNameLabel = new javax.swing.JLabel();
        cardHolderTextField = new javax.swing.JTextField();
        separator2 = new javax.swing.JLabel();
        deliveryPanel = new javax.swing.JPanel();
        personalInfoLabel1 = new javax.swing.JLabel();
        deliveryDateLabel = new javax.swing.JLabel();
        deliveryTimeComboBox = new javax.swing.JComboBox();
        deliveryDayComboBox = new javax.swing.JComboBox();
        deliverToMyAdressPanel = new javax.swing.JPanel();
        addressPanel = new guiproject.AddressPanel();
        deliverToMyAddressLabel = new javax.swing.JLabel();
        deliveryCheckBox = new javax.swing.JCheckBox();
        separator3 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        topPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        titleNameLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1121, 525));

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));

        personalInfoPanel.setBackground(new java.awt.Color(255, 255, 255));

        personalInfoLabel.setFont(new java.awt.Font("Gautami", 0, 18)); // NOI18N
        personalInfoLabel.setForeground(new java.awt.Color(51, 51, 51));
        personalInfoLabel.setText("Personlig information");

        firstNameLabel.setFont(new java.awt.Font("Gautami", 0, 14)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        firstNameLabel.setText("Förnamn");

        firstNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FirstNameUpdate(evt);
            }
        });

        lastNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LastNameUpdate(evt);
            }
        });

        lastNameLabel.setFont(new java.awt.Font("Gautami", 0, 14)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        lastNameLabel.setText("Efternamn");

        address1TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Address1Update(evt);
            }
        });

        adress1Label.setFont(new java.awt.Font("Gautami", 0, 14)); // NOI18N
        adress1Label.setForeground(new java.awt.Color(51, 51, 51));
        adress1Label.setText("Adress 1");

        address2TextField.setEditable(false);
        address2TextField.setBackground(new java.awt.Color(204, 204, 204));

        adress2Label.setFont(new java.awt.Font("Gautami", 0, 14)); // NOI18N
        adress2Label.setForeground(new java.awt.Color(153, 153, 153));
        adress2Label.setText("Adress 2");

        postCodeLabel.setFont(new java.awt.Font("Gautami", 0, 14)); // NOI18N
        postCodeLabel.setForeground(new java.awt.Color(51, 51, 51));
        postCodeLabel.setText("Postnummer");

        postCodeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PostCodeUpdate(evt);
            }
        });

        cityLabel.setFont(new java.awt.Font("Gautami", 0, 14)); // NOI18N
        cityLabel.setForeground(new java.awt.Color(153, 153, 153));
        cityLabel.setText("Ort");

        cityTextField.setEditable(false);
        cityTextField.setBackground(new java.awt.Color(204, 204, 204));

        emailLabel.setFont(new java.awt.Font("Gautami", 0, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(51, 51, 51));
        emailLabel.setText("E-mailadress");

        emailTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EmailUpdate(evt);
            }
        });

        separator1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redSeparator.png"))); // NOI18N
        separator1.setPreferredSize(new java.awt.Dimension(285, 2));

        phoneNumberTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phoneNumberUpdate(evt);
            }
        });

        phoneNumberLabel.setFont(new java.awt.Font("Gautami", 0, 14)); // NOI18N
        phoneNumberLabel.setForeground(new java.awt.Color(51, 51, 51));
        phoneNumberLabel.setText("Telefon");

        javax.swing.GroupLayout personalInfoPanelLayout = new javax.swing.GroupLayout(personalInfoPanel);
        personalInfoPanel.setLayout(personalInfoPanelLayout);
        personalInfoPanelLayout.setHorizontalGroup(
            personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(personalInfoPanelLayout.createSequentialGroup()
                            .addComponent(adress1Label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(address1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(personalInfoPanelLayout.createSequentialGroup()
                            .addComponent(lastNameLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(personalInfoPanelLayout.createSequentialGroup()
                            .addComponent(firstNameLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(personalInfoPanelLayout.createSequentialGroup()
                            .addComponent(personalInfoLabel)
                            .addGap(126, 126, 126))
                        .addGroup(personalInfoPanelLayout.createSequentialGroup()
                            .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(postCodeLabel)
                                .addComponent(adress2Label)
                                .addComponent(cityLabel)
                                .addComponent(emailLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(address2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(postCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalInfoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(phoneNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        personalInfoPanelLayout.setVerticalGroup(
            personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(personalInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adress1Label)
                    .addComponent(address1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adress2Label)
                    .addComponent(address2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postCodeLabel)
                    .addComponent(postCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLabel)
                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumberLabel))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        paymentInfoPanel.setBackground(new java.awt.Color(255, 255, 255));

        paymentInfoLabel.setFont(new java.awt.Font("Gautami", 0, 18)); // NOI18N
        paymentInfoLabel.setForeground(new java.awt.Color(51, 51, 51));
        paymentInfoLabel.setText("Betalning");

        cardNumberLabel.setFont(new java.awt.Font("Gautami", 0, 14)); // NOI18N
        cardNumberLabel.setForeground(new java.awt.Color(51, 51, 51));
        cardNumberLabel.setText("Kortnummer");

        cardNumberTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CardNumberUpdate(evt);
            }
        });

        cardTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VISA", "MasterCard", "PayPal" }));
        cardTypeComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cardTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardTypeUpdate(evt);
            }
        });

        cardTypeLabel.setFont(new java.awt.Font("Gautami", 0, 14)); // NOI18N
        cardTypeLabel.setForeground(new java.awt.Color(51, 51, 51));
        cardTypeLabel.setText("Korttyp");

        expirationDateLabel.setFont(new java.awt.Font("Gautami", 0, 14)); // NOI18N
        expirationDateLabel.setForeground(new java.awt.Color(51, 51, 51));
        expirationDateLabel.setText("Expiration date");

        validMonthComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        validMonthComboBox.setSelectedIndex(5);
        validMonthComboBox.setToolTipText("Månad");
        validMonthComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        validMonthComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidMonthUpdate(evt);
            }
        });

        expDateSlashLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        expDateSlashLabel.setForeground(new java.awt.Color(51, 51, 51));
        expDateSlashLabel.setText("/");

        validYearComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2016", "2017", "2018", "2019", "2020" }));
        validYearComboBox.setToolTipText("År");
        validYearComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        validYearComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidYearUpdate(evt);
            }
        });

        verificationCodeLabel.setFont(new java.awt.Font("Gautami", 0, 14)); // NOI18N
        verificationCodeLabel.setForeground(new java.awt.Color(51, 51, 51));
        verificationCodeLabel.setText("CVV");

        verificationCodeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                VerificationCodeUpdate(evt);
            }
        });

        cardHolderNameLabel.setFont(new java.awt.Font("Gautami", 0, 14)); // NOI18N
        cardHolderNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        cardHolderNameLabel.setText("Kortinnehavare");

        cardHolderTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CardHolderUpdate(evt);
            }
        });

        separator2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redSeparator.png"))); // NOI18N

        javax.swing.GroupLayout paymentInfoPanelLayout = new javax.swing.GroupLayout(paymentInfoPanel);
        paymentInfoPanel.setLayout(paymentInfoPanelLayout);
        paymentInfoPanelLayout.setHorizontalGroup(
            paymentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentInfoPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(paymentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paymentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(paymentInfoPanelLayout.createSequentialGroup()
                            .addGroup(paymentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cardNumberLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cardTypeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(expirationDateLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(verificationCodeLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(paymentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cardTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cardNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(paymentInfoPanelLayout.createSequentialGroup()
                                    .addComponent(validMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(expDateSlashLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(validYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(verificationCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(paymentInfoPanelLayout.createSequentialGroup()
                            .addComponent(cardHolderNameLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cardHolderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(separator2)
                    .addComponent(paymentInfoLabel))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        paymentInfoPanelLayout.setVerticalGroup(
            paymentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paymentInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paymentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardNumberLabel)
                    .addComponent(cardNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paymentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardTypeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paymentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expirationDateLabel)
                    .addComponent(validMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expDateSlashLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paymentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verificationCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verificationCodeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paymentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardHolderNameLabel)
                    .addComponent(cardHolderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deliveryPanel.setBackground(new java.awt.Color(255, 255, 255));

        personalInfoLabel1.setFont(new java.awt.Font("Gautami", 0, 18)); // NOI18N
        personalInfoLabel1.setForeground(new java.awt.Color(51, 51, 51));
        personalInfoLabel1.setText("Leverans");

        deliveryDateLabel.setFont(new java.awt.Font("Gautami", 0, 14)); // NOI18N
        deliveryDateLabel.setForeground(new java.awt.Color(153, 153, 153));
        deliveryDateLabel.setText("Leveranstid");

        deliveryTimeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10:00-12:00", "12:00-14:00", "14:00-16:00", "16:00-18:00", "18:00-20:00", "20:00-22:00" }));
        deliveryTimeComboBox.setSelectedIndex(1);
        deliveryTimeComboBox.setToolTipText("");
        deliveryTimeComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deliveryTimeComboBox.setEnabled(false);

        deliveryDayComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "idag", "imorgon", "i övermorgon" }));
        deliveryDayComboBox.setSelectedIndex(1);
        deliveryDayComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deliveryDayComboBox.setEnabled(false);

        deliverToMyAdressPanel.setBackground(new java.awt.Color(255, 255, 255));

        deliverToMyAddressLabel.setFont(new java.awt.Font("Gautami", 0, 14)); // NOI18N
        deliverToMyAddressLabel.setForeground(new java.awt.Color(153, 153, 153));
        deliverToMyAddressLabel.setText("Leverera till annan adress");

        deliveryCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        deliveryCheckBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deliveryCheckBox.setEnabled(false);
        deliveryCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deliverToMyAdressPanelLayout = new javax.swing.GroupLayout(deliverToMyAdressPanel);
        deliverToMyAdressPanel.setLayout(deliverToMyAdressPanelLayout);
        deliverToMyAdressPanelLayout.setHorizontalGroup(
            deliverToMyAdressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deliverToMyAdressPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deliverToMyAddressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deliveryCheckBox)
                .addGap(120, 120, 120))
            .addGroup(deliverToMyAdressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deliverToMyAdressPanelLayout.setVerticalGroup(
            deliverToMyAdressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deliverToMyAdressPanelLayout.createSequentialGroup()
                .addGroup(deliverToMyAdressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deliveryCheckBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deliverToMyAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(addressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        separator3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redSeparator.png"))); // NOI18N

        javax.swing.GroupLayout deliveryPanelLayout = new javax.swing.GroupLayout(deliveryPanel);
        deliveryPanel.setLayout(deliveryPanelLayout);
        deliveryPanelLayout.setHorizontalGroup(
            deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deliveryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deliveryPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(deliveryDateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deliveryTimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deliveryDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deliveryPanelLayout.createSequentialGroup()
                        .addComponent(deliverToMyAdressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(deliveryPanelLayout.createSequentialGroup()
                        .addGroup(deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(personalInfoLabel1)
                            .addComponent(separator3))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        deliveryPanelLayout.setVerticalGroup(
            deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deliveryPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(personalInfoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deliveryDateLabel)
                    .addComponent(deliveryTimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deliveryDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deliverToMyAdressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        saveButton.setBackground(new java.awt.Color(255, 255, 255));
        saveButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saveButton.setForeground(new java.awt.Color(0, 51, 0));
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/greenButton.png"))); // NOI18N
        saveButton.setText("Spara ändringar");
        saveButton.setToolTipText("Spara ändringar");
        saveButton.setBorder(null);
        saveButton.setBorderPainted(false);
        saveButton.setContentAreaFilled(false);
        saveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveButtonClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SaveButtonHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SaveButtonUnhover(evt);
            }
        });
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(personalInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(paymentInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deliveryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(personalInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(deliveryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(39, 39, 39)
                        .addComponent(saveButton))
                    .addComponent(paymentInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        topPanel.setBackground(new java.awt.Color(255, 255, 255));
        topPanel.setForeground(new java.awt.Color(255, 0, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Mitt konto -");

        titleNameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        titleNameLabel.setText("Namn");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titleNameLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleNameLabel))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deliveryCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryCheckBoxActionPerformed
        // Happens when the user checks/unchecks the delivery checkbox.
        
        if(deliveryCheckBox.isSelected()){
            addressPanel.setVisible(true);
        } else{
            addressPanel.setVisible(false);
        }
        
    }//GEN-LAST:event_deliveryCheckBoxActionPerformed
 
    // ------ Changes the icon for the save button -----------------------------
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        iMDH.shutDown();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void SaveButtonHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveButtonHover
        saveButton.setIcon(saveButtonHover);
    }//GEN-LAST:event_SaveButtonHover

    private void SaveButtonUnhover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveButtonUnhover
        saveButton.setIcon(saveButtonNormal);
        saveButton.setForeground(new Color(003400));
    }//GEN-LAST:event_SaveButtonUnhover

    private void SaveButtonClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveButtonClicked
        saveButton.setIcon(saveButtonClick);
        saveButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_SaveButtonClicked
    // -------------------------------------------------------------------------
    
    
    // ------ Personal information ---------------------------------------------
    private void phoneNumberUpdate(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumberUpdate
        iMDH.getCustomer().setPhoneNumber(phoneNumberTextField.getText());
    }//GEN-LAST:event_phoneNumberUpdate

    private void FirstNameUpdate(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FirstNameUpdate
        iMDH.getCustomer().setFirstName(firstNameTextField.getText());
    }//GEN-LAST:event_FirstNameUpdate

    private void LastNameUpdate(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LastNameUpdate
        iMDH.getCustomer().setLastName(lastNameTextField.getText());
    }//GEN-LAST:event_LastNameUpdate

    private void Address1Update(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Address1Update
        iMDH.getCustomer().setAddress(address1TextField.getText());
    }//GEN-LAST:event_Address1Update

    private void PostCodeUpdate(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PostCodeUpdate
        iMDH.getCustomer().setPostCode(postCodeTextField.getText());
    }//GEN-LAST:event_PostCodeUpdate

    private void EmailUpdate(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailUpdate
        iMDH.getCustomer().setEmail(emailTextField.getText());
    }//GEN-LAST:event_EmailUpdate
    // -------------------------------------------------------------------------
    
    
    // ------ Payment ----------------------------------------------------------
    private void CardNumberUpdate(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CardNumberUpdate
        iMDH.getCreditCard().setCardNumber(cardNumberTextField.getText());
    }//GEN-LAST:event_CardNumberUpdate

    private void VerificationCodeUpdate(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VerificationCodeUpdate
        try{
            iMDH.getCreditCard().setVerificationCode(Integer.parseInt(verificationCodeTextField.getText()));
        } catch(NumberFormatException nfe){
            System.out.println("Incorrect input.");
        }
    }//GEN-LAST:event_VerificationCodeUpdate

    private void CardHolderUpdate(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CardHolderUpdate
        iMDH.getCreditCard().setHoldersName(cardHolderTextField.getText());
    }//GEN-LAST:event_CardHolderUpdate

    private void CardTypeUpdate(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardTypeUpdate
        iMDH.getCreditCard().setCardType(cardTypeComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_CardTypeUpdate

    private void ValidMonthUpdate(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidMonthUpdate
        iMDH.getCreditCard().setValidMonth(validMonthComboBox.getSelectedIndex());
    }//GEN-LAST:event_ValidMonthUpdate

    private void ValidYearUpdate(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidYearUpdate
        iMDH.getCreditCard().setValidYear(validYearComboBox.getSelectedIndex());
    }//GEN-LAST:event_ValidYearUpdate
    // -------------------------------------------------------------------------
    
    
    IMatDataHandler iMDH = IMatDataHandler.getInstance();
    private final ImageIcon saveButtonNormal = new ImageIcon(getClass().getResource("/greenButton.png"));
    private final ImageIcon saveButtonHover = new ImageIcon(getClass().getResource("/greenButtonHover.png"));
    private final ImageIcon saveButtonClick = new ImageIcon(getClass().getResource("/greenButtonClick.png"));
    private boolean isInteger;   // remove????
    private JPanel otherAddressPanel = new AddressPanel();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address1TextField;
    private javax.swing.JTextField address2TextField;
    private guiproject.AddressPanel addressPanel;
    private javax.swing.JLabel adress1Label;
    private javax.swing.JLabel adress2Label;
    private javax.swing.JLabel cardHolderNameLabel;
    private javax.swing.JTextField cardHolderTextField;
    private javax.swing.JLabel cardNumberLabel;
    private javax.swing.JTextField cardNumberTextField;
    private javax.swing.JComboBox cardTypeComboBox;
    private javax.swing.JLabel cardTypeLabel;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel deliverToMyAddressLabel;
    private javax.swing.JPanel deliverToMyAdressPanel;
    private javax.swing.JCheckBox deliveryCheckBox;
    private javax.swing.JLabel deliveryDateLabel;
    private javax.swing.JComboBox deliveryDayComboBox;
    private javax.swing.JPanel deliveryPanel;
    private javax.swing.JComboBox deliveryTimeComboBox;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel expDateSlashLabel;
    private javax.swing.JLabel expirationDateLabel;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel paymentInfoLabel;
    private javax.swing.JPanel paymentInfoPanel;
    private javax.swing.JLabel personalInfoLabel;
    private javax.swing.JLabel personalInfoLabel1;
    private javax.swing.JPanel personalInfoPanel;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JLabel postCodeLabel;
    private javax.swing.JTextField postCodeTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel separator1;
    private javax.swing.JLabel separator2;
    private javax.swing.JLabel separator3;
    private javax.swing.JLabel titleNameLabel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JComboBox validMonthComboBox;
    private javax.swing.JComboBox validYearComboBox;
    private javax.swing.JLabel verificationCodeLabel;
    private javax.swing.JTextField verificationCodeTextField;
    // End of variables declaration//GEN-END:variables
}
